### ISSUE TITLE
This repo should be renamed

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/docker-image-size-checker#4]
Since the `product` for this is a simple groovy script, where incidentally we include a Dockerfile if you wanted to use the tool with a Docker image. 

I propose a rename, from `docker-image-size-checker` -> `image-size-checker`. As the convention at the time was to include docker in the name if the product was a docker image...which this s not. @lakruzz and @buep whaddya think?

**Comment by lakruzz** [comment]
@MadsNielsen 
I definitely vote for `image-size-checker`
